version: '3.2' 

services:
  db:
    image: mysql:8.0
    container_name: mysql01
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123
      
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp01
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql01:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123
volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local